# Generated by Django 4.2.1 on 2023-05-08 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Title",
                    models.CharField(
                        default="project", max_length=100, verbose_name="Project Title"
                    ),
                ),
                (
                    "Description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Project Description"
                    ),
                ),
                (
                    "Url_1",
                    models.TextField(blank=True, null=True, verbose_name="First Url"),
                ),
                (
                    "Url_2",
                    models.TextField(blank=True, null=True, verbose_name="Second Url"),
                ),
                (
                    "Url_3",
                    models.TextField(blank=True, null=True, verbose_name="Third Url"),
                ),
                (
                    "Url_4",
                    models.TextField(blank=True, null=True, verbose_name="Fourth Url"),
                ),
                (
                    "User",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
            },
        ),
    ]
