# Generated by Django 4.2.1 on 2023-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0002_alter_project_url_1_alter_project_url_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="XML",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
