# Generated by Django 4.2.1 on 2023-05-18 16:39

import Projects.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0004_alter_project_xml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="XML",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads",
                validators=[Projects.utils.validate_file_extension],
            ),
        ),
    ]
